### PR TITLE
Add support for Terraform v1.x

### PR DESCRIPTION
**Pull request by soerenmartius**
- feat: add support for Terraform v1.x
- chore: prepare v0.6.0 release

### CODE REVIEW

**Comment by mariux** [comment]
@soerenmartius what is the state... can we fix CI and get this released?

**Comment by mariux** [comment]
@soerenmartius see #33 for fixes to be applied to this branch

**Comment by soerenmartius** [comment]
needs another review @mariux

**Review by mariux — APPROVED** [review]
lgtm

**Pull request merged**
